//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nicom.Timesheets.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUserRateModel
    {
        public int Id { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
        public double UserRate { get; set; }
        public int UserPercentage { get; set; }
    
        public virtual ProjectModel Project { get; set; }
        public virtual UserModel User { get; set; }
    }
}
