//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nicom.Timesheets.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectModel
    {
        public ProjectModel()
        {
            this.ProjectUserRates = new HashSet<ProjectUserRateModel>();
            this.TimesheetEntries = new HashSet<TimesheetEntryModel>();
            this.UserTasks = new HashSet<UserTaskModel>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<float> EstimatedEffort { get; set; }
        public bool IsBillable { get; set; }
        public Nullable<int> ParentProjectId { get; set; }
        public Nullable<bool> IsFixedPrice { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<double> BarterPercentage { get; set; }
        public Nullable<double> FixedPriceAmount { get; set; }
        public bool RegularMaintenance { get; set; }
        public bool IsSRED { get; set; }
        public bool IsParentProject { get; set; }
        public Nullable<float> InternalEstimatedHours { get; set; }
        public Nullable<System.DateTime> ProjectedStartDate { get; set; }
        public Nullable<System.DateTime> ProjectedEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public Nullable<int> SalemanID { get; set; }
        public Nullable<int> Salesman1ID { get; set; }
        public Nullable<double> SalesmanPercentage { get; set; }
        public Nullable<double> Salesman1Percentage { get; set; }
    
        public virtual ClientModel Client { get; set; }
        public virtual ICollection<ProjectUserRateModel> ProjectUserRates { get; set; }
        public virtual ICollection<TimesheetEntryModel> TimesheetEntries { get; set; }
        public virtual ICollection<UserTaskModel> UserTasks { get; set; }
    }
}
