//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nicom.Timesheets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientUserRates = new HashSet<ClientUserRate>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ClientLongName { get; set; }
        public string InvoiceType { get; set; }
        public bool IsBarterClient { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public bool HasTimeBlock { get; set; }
        public Nullable<double> BarterPercentage { get; set; }
        public Nullable<int> SalemanID { get; set; }
        public Nullable<int> Salesman1ID { get; set; }
        public Nullable<double> SalesmanPercentage { get; set; }
        public Nullable<double> Salesman1Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientUserRate> ClientUserRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}
