//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nicom.Timesheets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetEntry
    {
        public int Id { get; set; }
        public int TimesheetId { get; set; }
        public int ClientId { get; set; }
        public int ProjectId { get; set; }
        public string Description { get; set; }
        public Nullable<float> Sat { get; set; }
        public Nullable<float> Sun { get; set; }
        public Nullable<float> Mon { get; set; }
        public Nullable<float> Tue { get; set; }
        public Nullable<float> Wed { get; set; }
        public Nullable<float> Thu { get; set; }
        public Nullable<float> Fri { get; set; }
        public bool Billable { get; set; }
        public Nullable<bool> SchedAfterHours { get; set; }
        public Nullable<bool> UnschedAfterHours { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Timesheet Timesheet { get; set; }
    }
}
