//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nicom.Timesheets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timesheet()
        {
            this.TimesheetEntries = new HashSet<TimesheetEntry>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> WeekStartingDate { get; set; }
        public Nullable<System.DateTime> WeekEndingDate { get; set; }
        public string UserName { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetEntry> TimesheetEntries { get; set; }
        public virtual User User { get; set; }
    }
}
